### PR TITLE
user, system install and support RedHat

### PR DESCRIPTION
**Pull request by hatappi**
Hello.
I'm using CentOS.
But this role doesn't support RedHat. So I implemented it.
And I also implemented `system` install.

## TODO
- add options
    - `pyenv_env`: user or system. **default** is user
    - `pyenv_setting_path `: pyenv env variables settting path. **default** if pyenv_env is user, this option is `~/.bashrc`
    - `pyenv_global`: If this option is defined, call `pyenv global xxxx`.
- add RedHat.yml

### Environment
- centos 6
- centos 7
- ubuntu trusty64
- ubuntu xenial64

### playbook

**system install**

```
- hosts: all 
  vars:
    pyenv_env: "system"
  roles:
    - ansible-galaxy-pyenv
```

**user install**

```
- hosts: all 
  roles:
    - ansible-galaxy-pyenv
```

### CODE REVIEW

**Comment by hatappi** [comment]
@avanov 
Hello.
Please check this Pull Request.

**Comment by avanov** [comment]
Hi @hatappi 

it's awesome! Could you also uncomment relevant metadata section in https://github.com/avanov/ansible-galaxy-pyenv/blob/master/meta/main.yml (for Ansible Galaxy registry), and add new default variables to https://github.com/avanov/ansible-galaxy-pyenv/blob/master/README.md#role-variables
Thanks!

**Comment by hatappi** [comment]
Hi @avanov 
Thank you for review pull requests.
I uncommented a relevant metadata section and added new version. ref: https://github.com/avanov/ansible-galaxy-pyenv/pull/11/commits/a8888cc61d7eddc41659169eebd8d7df479ceb20
And I add new default values to README.md ref: https://github.com/avanov/ansible-galaxy-pyenv/pull/11/commits/731d8c3d86da1caf084bd70e337709774c7ea680

**Comment by avanov** [comment]
Thanks! Great stuff!

**Pull request merged**
