### PR TITLE
Updating of existing pyenv installs should default to no

### PR DESCRIPTION
**Pull request by alonisser**
Bumped into this now, running the role (just to install a new virtualenv) ended up in updating pyenv from master and introducing a bug..  Most of the times I don't need this,

### CODE REVIEW

**Comment by avanov** [comment]
Hey @alonisser! Thanks for the good point.
The PR seems good apart a few conventions that I want to follow:
* Template placeholders for pyenv have to start with the "pyenv_" prefix.
* Template placeholders have to be quoted when used as a value inside a role recipe.

So, could you rename the placeholder and quote them like this?
 ``update: "{{pyenv_update_git_checkout}}"``

**Comment by alonisser** [comment]
No problems, updating



Twitter:@alonisser <https://twitter.com/alonisser>
LinkedIn Profile <http://www.linkedin.com/in/alonisser>
Facebook <https://www.facebook.com/alonisser>
*Tech blog:*4p-tech.co.il/blog
*Personal Blog:*degeladom.wordpress.com
Tel:972-54-6734469

**Comment by alonisser** [comment]
Updated with the fixes

**Comment by avanov** [comment]
Ok, now how about changing the name of the placeholder to ``pyenv_update_git_install``? I want it to be short and still indicating what gets done under the hood (i.e. git checkout).

**Comment by alonisser** [comment]
done

**Comment by avanov** [comment]
Awesome! Thanks for bearing with me and for providing the patch :)

**Comment by avanov** [comment]
I will re-import the role on the Galaxy website later this day.

**Comment by avanov** [comment]
Done. You can try to pull it from the Galaxy.

**Comment by alonisser** [comment]
Thanks!



Twitter:@alonisser <https://twitter.com/alonisser>
LinkedIn Profile <http://www.linkedin.com/in/alonisser>
Facebook <https://www.facebook.com/alonisser>
*Tech blog:*4p-tech.co.il/blog
*Personal Blog:*degeladom.wordpress.com
Tel:972-54-6734469

**Pull request merged**
