### PR TITLE
Fix deprecation warnings in package installation

### PR DESCRIPTION
**Pull request by Dutchy-**
This fixes deprecation warnings in package installation

### CODE REVIEW

**Comment by Dutchy-** [comment]
Do you have time to consider this PR?

**Comment by avanov** [comment]
@Dutchy- I haven't been following Ansible lately, could you point me to the changelog/docs where `with_items` was turned to a deprecated mode, for reference purposes?

**Comment by rouge8** [comment]
The errors look like:

```
[DEPRECATION WARNING]: Invoking "apt" only once while using a loop via squash_actions is deprecated. Instead of using a loop to supply multiple items and specifying `pkg: "{{ item }}"`,
please use `pkg: '{{ pyenv_debian_packages }}'` and remove the loop. This feature will be removed in version 2.11. Deprecation warnings can be disabled by setting deprecation_warnings=False
 in ansible.cfg.
```

I think it comes from https://github.com/ansible/ansible/pull/35978 and is mentioned here: https://docs.ansible.com/ansible/latest/porting_guides/porting_guide_2.7.html#using-a-loop-on-a-package-module-via-squash-actions

**Comment by avanov** [comment]
@rouge8 amazing, thanks!
@Dutchy- Thank you, I'm going to merge this one now, and then update the galaxy.

**Pull request merged**
