### PR TITLE
Add Github actions to deploy action

### PR DESCRIPTION
**Pull request by staticdev**
Summary of changes:
- Add github actions for labels and release
- Add pre-commit checks for end-of-files, yamllint and ansible-lint
- Fixed linting issues
- Added integration tests

To use the release action, the only thing you have to do is configure on your repo a secret GALAXY_TOKEN with your token and create a release on Github. It will send it to Galaxy =)

### CODE REVIEW

**Comment by staticdev** [comment]
@avanov how about trying this to release a new version?

**Comment by avanov** [comment]
I prefer not adding these automations. Github CI is nice, but bots are not so. Also, linting and formatting are too opinionated and I tend to disagree with them.

**Comment by staticdev** [comment]
> I prefer not adding these automations. Github CI is nice, but bots are not so. Also, linting and formatting are too opinionated and I tend to disagree with them.

I added just the linters used by Ansible Galaxy to grade the roles. If you see there the grade of this role is 3.9 there (https://galaxy.ansible.com/avanov/pyenv) opinionated or not, the users see that grade when choosing which role to use. As you also can see here (https://galaxy.ansible.com/staticdev/ansible_galaxy_pyenv) this PR just bumps the grade to 5.0 (maximum). Of course it is your call as the owner of the repo to accept or not.

**Comment by avanov** [comment]
It's unfortunate that the grade the Galaxy uses depends on the styling of the source instead of its overall stability/safety/correctness (not claiming the source is stable an/or correct though, just an observation what the community considers important). I appreciate your effort nonetheless.

**Comment by avanov** [comment]
I may extract the parts of Github CI from your PR sometime in the future, as I wanted to migrate from Travis anyways. Not sure when though, Ansible is no longer my primary provisioning solution, I mostly use Nix nowadays.

**Pull request closed without merging**
