### PR TITLE
load pyenv autocomplete file for bash

### PR DESCRIPTION
**Pull request by jbouzekri**
Everything is in the title ;)

### CODE REVIEW

**Comment by jbouzekri** [comment]
Could you merge this if possible and publish the new version to ansible galaxy ?

Thx

**Comment by avanov** [comment]
I didn't have enough time last time. Will review it and merge and publish during this week. Thanks!

**Comment by jbouzekri** [comment]
No problem. I contacted you again because our deployment script which uses your role will go in production at the end of next month. Thx again.

**Comment by avanov** [comment]
@jbouzekri glad to hear it helped!
I've just taken a brief look at pyenv docs and [it says](https://github.com/yyuu/pyenv#advanced-configuration) that autocompletion is optional and non0required for generic installs. Could you add a  [boolean variable for enabling/disabling](https://github.com/avanov/ansible-galaxy-pyenv/blob/master/defaults/main.yml) that feature as part of your PR (I prefer it to be opt-out by default). Something like `pyenv_enable_autocompletion: no`.

**Comment by jbouzekri** [comment]
No problem. I will do this tomorrow.

**Comment by avanov** [comment]
thanks!

**Comment by jbouzekri** [comment]
@avanov : done. I rebased everything in a single commit. Let me know if you want me to change anything.

**Comment by avanov** [comment]
Wonderful! Thanks!

**Comment by avanov** [comment]
I've just re-imported the role on Galaxy.

**Comment by jbouzekri** [comment]
Awesome. Thx.

**Pull request merged**
