### PR TITLE
pyenv should update its python list before trying to install

### PR DESCRIPTION
**Pull request by t0k4rt**
Hi, 
When you have an old pyenv install, the python versions liste is not up to date.
So if you try to install another version of python, it might not be in the pyenv list.

To solve this issue we can update pyenv every time we try we try to install a version of python.

This is a small change that implement this.
Thanks

### CODE REVIEW

**Comment by t0k4rt** [comment]
I've added an option, 
but I've kept the installation of the update plugin which does not depend on the `pyenv_update` option if you're okay with that

**Comment by avanov** [comment]
> Since you also install virtualenv plugin, we should stay in line and install by default the plugin.

My reasoning of that flag was different, though - if `pyenv_update` is enabled, the playbook makes sure that the list of python versions is going to be updated, and it might require a plugin to do so. Otherwise, there's no need for a plugin. In other words, the flag provides an extension that contains two extra steps - installing the plugin and updating the list of python versions, and it is not possible to just install the plugin but keep the list of python versions not updated.

In terms of consistency, we might consider `pyenv_virtualenvs` to be a flag for installing a virtualenv plugin, I don't mind it.

**Comment by t0k4rt** [comment]
No problems I'll change that.

**Comment by avanov** [comment]
Thanks! Great stuff!
And sorry for the delays, had a lot of paperwork for the past two weeks.

**Comment by t0k4rt** [comment]
Thanks !

**Pull request merged**
